In [3]:
import pandas as pd
import numpy as np
data = pd.read_csv("D:\\Python\\MachineLearning\\MachineLearning\\week03\\data\\framingham.csv")
data.isnull().sum()
data = data.dropna(how="any", axis=0)

male = data['male'].tolist() 
X1 = np.asarray(male) 

age = data['age'].tolist() 
X2 = np.asarray(age) 

education = data['education'].tolist() 
X3 = np.asarray(education) 

currentSmoker = data['currentSmoker'].tolist() 
X4 = np.asarray(currentSmoker) 

cigsPerDay = data['cigsPerDay'].tolist() 
X5 = np.asarray(cigsPerDay) 

BPMeds = data['BPMeds'].tolist() 
X6 = np.asarray(BPMeds) 

prevalentStroke = data['prevalentStroke'].tolist() 
X7 = np.asarray(prevalentStroke) 

prevalentHyp = data['prevalentHyp'].tolist() 
X8 = np.asarray(prevalentHyp) 

diabetes = data['diabetes'].tolist() 
X9 = np.asarray(diabetes) 

totChol = data['totChol'].tolist() 
X10 = np.asarray(totChol) 

sysBP = data['sysBP'].tolist() 
X11 = np.asarray(sysBP) 

diaBP = data['diaBP'].tolist() 
X12 = np.asarray(diaBP) 

BMI = data['BMI'].tolist() 
X13 = np.asarray(BMI) 

heartRate = data['heartRate'].tolist() 
X14 = np.asarray(heartRate) 

glucose = data['glucose'].tolist() 
X15 = np.asarray(glucose) 

TenYearCHD = data['TenYearCHD'].tolist() 
y = np.asarray(TenYearCHD)

In [4]:
def sigmoid(s, clip_threshold=20):
    clipped_s = np.clip(s, -clip_threshold, clip_threshold)
    return 1 / (1 + np.exp(-clipped_s))

def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 10000): 
# method to calculate model logistic regression by Stochastic Gradient Descent method 
# eta: learning rate; tol: tolerance; max_count: maximum iterates 
    w = [w_init]     
    it = 0 
    N = X.shape[1] 
    d = X.shape[0] 
    count = 0 
    check_w_after = 20
# loop of stochastic gradient descent  
    while count < max_count: 
        # shuffle the order of data (for stochastic gradient descent).  
        # and put into mix_id  
        mix_id = np.random.permutation(N) 
        for i in mix_id: 
            xi = X[:, i].reshape(d, 1) 
            yi = y[i] 
            zi = sigmoid(np.dot(w[-1].T, xi)) 
            w_new = w[-1] + eta*(yi - zi)*xi 
            count += 1 
            # stopping criteria 
            if count%check_w_after == 0:                 
                if np.linalg.norm(w_new - w[-check_w_after]) < tol: 
                    return w 
            w.append(w_new) 
    return w

In [23]:
eta = .05  
d = X.shape[0] 
w_init = np.random.randn(d, 1) 
 
w = logistic_sigmoid_regression(X, y, w_init, eta) 
print(w[-1]) 

[[ -0.58375355]
 [  2.04318687]
 [  2.84543659]
 [ -0.59905614]
 [ -0.65911161]
 [  2.78880003]
 [ -0.4875276 ]
 [  0.04440762]
 [  0.89186609]
 [  0.10727018]
 [ -3.10757965]
 [ 15.99865144]
 [ -9.28425757]
 [ -5.4370611 ]
 [-29.02691289]
 [  7.27135972]]


In [24]:
sigmoid_outputs = sigmoid(np.dot(w[-1].T, X))
print(sigmoid_outputs)
# Phân loại các giá trị
classified_values = np.where(sigmoid_outputs >= 0.5, 1, 0)

print(classified_values)

[[2.06115362e-09 2.06115362e-09 2.06115362e-09 ... 2.06115362e-09
  2.06115362e-09 2.06115362e-09]]
[[0 0 0 ... 0 0 0]]


In [12]:
# Sử dụng thư viện scikit-learn 
from sklearn import linear_model 
logReg = linear_model.LogisticRegression(penalty=None) 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Add a column of ones to the left of the matrix X to get Xbar
N = X1.shape[0]
X = np.array([np.ones((N)), X1.T, X2.T, X3.T, X4.T, X5.T, X6.T, X7.T, X8.T, X9.T, X10.T, X11.T, X12.T, X13.T, X14.T, X15.T])
print(X.shape)
print(y.shape)
# Assuming X and y are your feature matrix and target vector
X_train, X_val, y_train, y_val = train_test_split(X.T, y, test_size=0.3, random_state=42)
logReg.fit(X_train, y_train)
print(X_train.shape)
# # Prediction
predict = logReg.predict(X_val) 
print(predict)
# For showing of w 
print(logReg.coef_)

# Tính toán Accuracy
accuracy = accuracy_score(y_val, predict)

# Tính toán Precision
precision = precision_score(y_val, predict)

# Tính toán Recall
recall = recall_score(y_val, predict)

# In kết quả
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

(16, 3656)
(3656,)
(2559, 16)
[0 0 0 ... 0 0 0]
[[-4.45421377e-01  5.39434719e-01  2.89174521e-02 -2.08755675e-01
  -1.80837474e-01  2.11505072e-02  2.28399793e-01  1.19907984e-01
   1.01104522e+00  2.33196289e-01  2.16478040e-04  1.11156726e-02
  -1.75255841e-02 -5.14573154e-02 -2.53711553e-02  5.47060324e-03]]
Accuracy: 0.8468550592525068
Precision: 0.6666666666666666
Recall: 0.06896551724137931


c:\Users\FPT SHOP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
