In [1]:
from sklearn.datasets import fetch_20newsgroups_vectorized
from sklearn.model_selection import train_test_split
import numpy as np
n_samples = 20000
X, y = fetch_20newsgroups_vectorized(subset='all', return_X_y=True)
X = X[:n_samples]
y = y[:n_samples]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,stratify=y, test_size=0.1)

train_samples, n_features = X_train.shape
n_classes = np.unique(y).shape[0]

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import sklearn 
#from sklearn.preprocessing import StandardScaler  
from sklearn.linear_model import LogisticRegression 

# Call to Logistic Regression Model - SAG: solving is based on Stochastic Average Gradient 
lorg=LogisticRegression(multi_class='multinomial',solver='sag', max_iter=5000) 
# and train model by Training Dataset 
lorg.fit(X_train,y_train)  
 
# Then Predict the Test data 
Y_pred=lorg.predict(X_test) 
 
# for accuracy 
from sklearn.metrics import accuracy_score 
print("Accuracy Score: ")
print(accuracy_score(y_test,Y_pred)) 
 
# for confusion matrix 
from sklearn.metrics import confusion_matrix 
cm=confusion_matrix(y_test,Y_pred) 
print("Confusion Matrix:")
print(cm) 
print("Coefficients:")
print(lorg.coef_)
y_predict = lorg.predict(X_test)
print("Predict:")
print(y_predict)

Accuracy Score: 
0.823342175066313
Confusion Matrix:
[[68  0  0  0  0  0  0  0  0  1  0  1  0  1  0  4  0  2  0  3]
 [ 0 79  3  1  0  5  2  0  0  0  0  1  1  1  1  1  0  1  0  1]
 [ 0  5 78  6  1  4  2  0  1  0  0  0  1  0  1  0  0  0  0  0]
 [ 0  4  8 67  4  1  4  1  1  0  0  1  3  2  0  0  0  1  1  0]
 [ 0  3  2  8 74  1  2  0  0  0  0  0  3  0  0  1  1  1  0  0]
 [ 0  4  7  3  1 81  0  1  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  2  2 82  4  0  1  1  1  1  1  0  1  0  0  0  0]
 [ 0  1  0  0  0  0  2 92  0  0  0  0  1  2  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  3  6 86  1  0  0  0  1  1  0  0  0  1  0]
 [ 0  1  0  1  0  1  2  0  0 87  4  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  3 92  0  0  0  0  0  0  0  1  0]
 [ 0  2  0  1  1  4  2  0  1  2  1 82  0  0  0  0  2  1  0  0]
 [ 0  4  0  1  1  1  2  4  0  0  0  0 84  0  1  0  0  0  0  0]
 [ 0  1  0  0  0  0  3  3  2  1  0  1  1 80  3  1  0  2  1  0]
 [ 1  1  0  0  1  2  2  0  0  0  0  0  0  3 88  1  0  0  0  0]
 [